// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Spryhb4lrOalCoqF6KERk6iJQNNLGL0',
    appId: '1:685435500986:web:8cdcab9e601ef01a684583',
    messagingSenderId: '685435500986',
    projectId: 'pictoapp-342ec',
    authDomain: 'pictoapp-342ec.firebaseapp.com',
    databaseURL: 'https://pictoapp-342ec-default-rtdb.firebaseio.com',
    storageBucket: 'pictoapp-342ec.appspot.com',
    measurementId: 'G-H0VSLF6M08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFAyzxuaioJqK-QqJEF6-Rkw_BC7JkGg',
    appId: '1:1268217098:android:e50d75fa39c9e8610e36f3',
    messagingSenderId: '1268217098',
    projectId: 'pictoapp-edcf7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevpdtHVFxyqBGpxMfGsRPnMk9bCv4hko',
    appId: '1:685435500986:ios:150a398ef4389543684583',
    messagingSenderId: '685435500986',
    projectId: 'pictoapp-342ec',
    databaseURL: 'https://pictoapp-342ec-default-rtdb.firebaseio.com',
    storageBucket: 'pictoapp-342ec.appspot.com',
    iosBundleId: 'com.example.pictoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCevpdtHVFxyqBGpxMfGsRPnMk9bCv4hko',
    appId: '1:685435500986:ios:150a398ef4389543684583',
    messagingSenderId: '685435500986',
    projectId: 'pictoapp-342ec',
    databaseURL: 'https://pictoapp-342ec-default-rtdb.firebaseio.com',
    storageBucket: 'pictoapp-342ec.appspot.com',
    iosBundleId: 'com.example.pictoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Spryhb4lrOalCoqF6KERk6iJQNNLGL0',
    appId: '1:685435500986:web:0c90b6b4a66fec31684583',
    messagingSenderId: '685435500986',
    projectId: 'pictoapp-342ec',
    authDomain: 'pictoapp-342ec.firebaseapp.com',
    databaseURL: 'https://pictoapp-342ec-default-rtdb.firebaseio.com',
    storageBucket: 'pictoapp-342ec.appspot.com',
    measurementId: 'G-3CD8WGHG0L',
  );
}